# Generated by Django 4.0.6 on 2022-07-21 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productvariant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvariantprice', to='product.product'),
        ),
    ]
